
import type { Metadata, Viewport } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { i18n, type Locale } from '@/i18n-config';

const openSans = Open_Sans({
  subsets: ['latin', 'latin-ext'], // Add latin-ext for French/Portuguese characters
  variable: '--font-open-sans',
});

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: 'CodeBarreGenerator.com - Générateur de Code Barre Gratuit',
  description: 'Générez facilement des codes barres EAN, QR, Code 128 et plus. Personnalisable et gratuit. CodeBarreGenerator.com: simple, rapide et gratuit.',
  keywords: ['generateur code barre', 'générateur de code barre', 'code barre generator', 'gerador codigo de barras', 'gerador de codigo de barras gratuito', 'EAN-13', 'QR Code', 'Code 128'],
  alternates: {
    // Canonical will be auto-generated by Next.js per page based on metadataBase
    languages: {
      'fr': 'https://www.codebarregenerator.com/fr/',
      'pt': 'https://www.codebarregenerator.com/pt/',
      'x-default': 'https://www.codebarregenerator.com/fr/',
    },
  },
  metadataBase: new URL('https://www.codebarregenerator.com'),
  openGraph: {
    title: 'CodeBarreGenerator.com - Générateur de Code Barre Gratuit',
    description: 'Générez facilement des codes barres EAN, QR, Code 128 et plus. Personnalisable et gratuit. CodeBarreGenerator.com: simple, rapide et gratuit.',
    url: 'https://www.codebarregenerator.com',
    siteName: 'CodeBarreGenerator.com',
    images: [
      {
        url: '/og-image.png', // Updated to reference local public image
        width: 1200,
        height: 630,
        alt: 'Logo de CodeBarreGenerator.com et exemples de codes barres générés - generateur code barre',
        'data-ai-hint': 'barcode social media' as any,
      },
    ],
    locale: 'fr_FR', // Default locale
    alternateLocale: ['pt_PT'],
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'CodeBarreGenerator.com - Générateur de Code Barre Gratuit et Efficace',
    description: 'Créez et personnalisez vos codes barres (EAN, QR, etc.) gratuitement sur CodeBarreGenerator.com.',
    // siteId: 'YourTwitterSiteID', // Optional: Your Twitter user ID
    // creator: '@YourTwitterHandle', // Optional: Your Twitter handle
    // creatorId: 'YourTwitterCreatorID', // Optional: Your Twitter user ID for the content creator
    images: ['/twitter-image.png?data-ai-hint=barcode-twitter-card'], // Updated to reference local public image
  },
  icons: { 
    icon: '/favicon.ico',
    shortcut: '/favicon-16x16.png',
    apple: '/apple-touch-icon.png',
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#D6E4FF' }, // Light Blue
    { media: '(prefers-color-scheme: dark)', color: '#1A2B45' }, // Dark equivalent
  ],
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={params?.lang || i18n.defaultLocale} dir={params?.lang === 'ar' ? 'rtl' : 'ltr'}>
      <body className={`${openSans.variable} font-sans antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
